# Source - https://stackoverflow.com/a/63009069
# Posted by DannyB, modified by community. See post 'Timeline' for change history
# Retrieved 2026-03-03, License - CC BY-SA 4.0

name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
      run: |
        echo "KEYSTORE_BASE64:" >> secrets.txt
        echo $KEYSTORE_BASE64 >> secrets.txt
        echo "KEYSTORE_PASSWORD:" >> secrets.txt
        echo $KEYSTORE_PASSWORD >> secrets.txt
        echo "KEY_ALIAS:" >> secrets.txt
        echo $KEY_ALIAS >> secrets.txt
        echo "GOOGLE_PLAY_SERVICE_ACCOUNT_JSON:" >> secrets.txt
        echo $GOOGLE_PLAY_SERVICE_ACCOUNT_JSON >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
